### ISSUE TITLE
Responsive interface

### ISSUE THREAD

**Issue by Alejandroid17** [Alejandroid17/wikistorage#10]
# Information

When the device's screen is small, the interface is not responsive.

![Screenshot from 2021-03-18 19-53-10](https://user-images.githubusercontent.com/17381133/111681789-f0326700-8823-11eb-8c56-be7f220efa77.png)

## TODO

- [x] Responsive header
  - [x] Hide 'WikiStorage' title
  - [x] Show dark mode and compact mode buttons
- [x] Display content as a list
